language: cpp

os: linux

compiler:
    - gcc
    - clang

before_script:
    - mkdir build
    - cd build
    - cmake -DOPENCV_VERSION="3.4.8" -DCMAKE_CONFIGURATION_TYPES="Release" ..

script:
    - make
